# 02 – Preprocessing
Ziel: 10-Min → stündlich, Features bauen, final_dataset.csv speichern.

In [11]:
import importlib
import pandas as pd
import numpy as np
import sys
sys.path.append('..')

import src.data.load_data as load_data_module
import src.data.feature_engineering as feature_engineering_module

importlib.reload(load_data_module)
importlib.reload(feature_engineering_module)

load_production = load_data_module.load_production
get_production_path = load_data_module.get_production_path
build_final_dataset = feature_engineering_module.build_final_dataset

## Rohdaten laden

In [12]:
df_raw = load_production(sites=["Schonungen", "Schwanfeld", "Trabelsdorf"])
print(f'Rohdaten: {df_raw.shape} Zeilen')
df_raw.head()

Schonungen: 12 Datei(en)
  Lade: 2014_10-Min-Daten WP Schonungen.xlsx
  Lade: 2015_10-Min-Daten WP Schonungen.xlsx
  Lade: 2016_10-Min-Daten WP Schonungen.xlsx
  Lade: 2017_10-Min-Daten WP Schonungen.xlsx
  Lade: 2018_10-Min-Daten WP Schonungen.xlsx
  Lade: 2019_10-Min-Daten WP Schonungen.xlsx
  Lade: 2020_10-Min-Daten WP Schonungen.xlsx
  Lade: 2021_10-Min-Daten WP Schonungen.xlsx
  Lade: 2022_10-Min-Daten WP Schonungen.xlsx
  Lade: 2023_10-Min-Daten WP Schonungen.xlsx
  Lade: 2024_10-Min-Daten WP Schonungen.xlsx
  Lade: 2025_10-Min-Daten WP Schonungen.xlsx

Schwanfeld: 10 Datei(en)
  Lade: 2016_10-Min-Daten WEA Schwanfeld.xlsx
  Lade: 2017_10-Min-Daten WEA Schwanfeld.xlsx
  Lade: 2018_10-Min-Daten WEA Schwanfeld.xlsx
  Lade: 2019_10-Min-Daten WEA Schwanfeld.xlsx
  Lade: 2020_10-Min-Daten WEA Schwanfeld.xlsx
  Lade: 2021_10-Min-Daten WEA Schwanfeld.xlsx
  Lade: 2022_10-Min-Daten WEA Schwanfeld.xlsx
  Lade: 2023_10-Min-Daten WEA Schwanfeld.xlsx
  Lade: 2024_10-Min-Daten WEA Schwanfeld.xlsx
  Lade: 2025_10-Min-Daten WEA Schwanfeld.xlsx

Trabelsdorf: 9 Datei(en)
  Lade: 2017_10-Min-Daten WP Trabelsdorf.xlsx
  Lade: 2018_10-Min-Daten WP Trabelsdorf.xlsx
  Lade: 2019_10-Min-Daten WP Trabelsdorf.xlsx
  Lade: 2020_10-Min-Daten WP Trabelsdorf.xlsx
  Lade: 2021_10-Min-Daten WP Trabelsdorf.xlsx
  Lade: 2022_10-Min-Daten WP Trabelsdorf.xlsx
  Lade: 2023_10-Min-Daten WP Trabelsdorf.xlsx
  Lade: 2024_10-Min-Daten WP Trabelsdorf.xlsx
  Lade: 2025_10-Min-Daten WP Trabelsdorf.xlsx

==================================================
Gesamt: 4,501,324 Zeilen
Standorte: ['Schonungen', 'Schwanfeld', 'Trabelsdorf']
Zeitraum:  2014-01-02 00:00:00 bis 2025-08-31 23:50:00
Rohdaten: (4501324, 4) Zeilen

   timestamp power wind_speed        site
0 2014-01-02   403        6.1  Schonungen
1 2014-01-02   208        4.7  Schonungen
2 2014-01-02   397        6.2  Schonungen
3 2014-01-02   182          5  Schonungen
4 2014-01-02   385        6.3  Schonungen

## Auf Stundenwerte aggregieren + Features bauen

In [13]:
df = build_final_dataset(df_raw)
print(f'Stündliche Daten: {df.shape} Zeilen')
df.head(10)

Stündliche Daten: (254067, 11) Zeilen

,site,timestamp,power,wind_speed,hour,dayofweek,month,hour_sin,hour_cos,dow_sin,dow_cos
0,Schonungen,2014-01-02 00:00:00,249.833333,5.353333,0,3,1,0.000000,1.000000e+00,0.433884,-0.900969
1,Schonungen,2014-01-02 01:00:00,356.6,5.966667,1,3,1,0.258819,9.659258e-01,0.433884,-0.900969
2,Schonungen,2014-01-02 02:00:00,357.9,5.98,2,3,1,0.500000,8.660254e-01,0.433884,-0.900969
3,Schonungen,2014-01-02 03:00:00,256.266667,5.366667,3,3,1,0.707107,7.071068e-01,0.433884,-0.900969
4,Schonungen,2014-01-02 04:00:00,223.9,5.183333,4,3,1,0.866025,5.000000e-01,0.433884,-0.900969
5,Schonungen,2014-01-02 05:00:00,376.433333,6.036667,5,3,1,0.965926,2.588190e-01,0.433884,-0.900969
6,Schonungen,2014-01-02 06:00:00,306.033333,5.65,6,3,1,1.000000,6.123234e-17,0.433884,-0.900969
7,Schonungen,2014-01-02 07:00:00,253.4,5.253333,7,3,1,0.965926,-2.588190e-01,0.433884,-0.900969
8,Schonungen,2014-01-02 08:00:00,671.966667,7.176667,8,3,1,0.866025,-5.000000e-01,0.433884,-0.900969
9,Schonungen,2014-01-02 09:00:00,1134.8,8.593333,9,3,1,0.707107,-7.071068e-01,0.433884,-0.900969

## Qualitätsprüfung

In [14]:
print('Fehlende Werte:')
print(df.isnull().sum())
print(f'\nZeitraum: {df.timestamp.min()} bis {df.timestamp.max()}')
print(f'Anzahl Stunden: {len(df)}')
print(f'Vollständig? {len(df)} / {365*24*11*3} erwartet')

Fehlende Werte:
site          0
timestamp     0
power         0
wind_speed    0
hour          0
dayofweek     0
month         0
hour_sin      0
hour_cos      0
dow_sin       0
dow_cos       0
dtype: int64

Zeitraum: 2014-01-02 00:00:00 bis 2025-08-31 23:00:00
Anzahl Stunden: 254067
Vollständig? 254067 / 289080 erwartet

## Datensatz speichern
Dieser CSV ist der einzige Input für alle weiteren Notebooks.

In [15]:
df.to_csv('../data/processed/final_dataset.csv', index=False)
print('Gespeichert: data/processed/final_dataset.csv')
df.describe()

Gespeichert: data/processed/final_dataset.csv

,timestamp,hour,dayofweek,month,hour_sin,hour_cos,dow_sin,dow_cos
count,254067,254067.000000,254067.000000,254067.000000,2.540670e+05,2.540670e+05,254067.000000,254067.000000
mean,2020-09-24 17:09:52.468916,11.479681,3.001248,6.471364,1.472278e-03,2.445599e-04,-0.000371,0.000220
min,2014-01-02 00:00:00,0.000000,0.000000,1.000000,-1.000000e+00,-1.000000e+00,-0.974928,-0.900969
25%,2018-05-26 11:30:00,5.000000,1.000000,4.000000,-7.071068e-01,-7.071068e-01,-0.781831,-0.900969
50%,2020-10-24 16:00:00,11.000000,3.000000,6.000000,1.224647e-16,6.123234e-17,0.000000,-0.222521
75%,2023-03-27 16:30:00,17.000000,5.000000,9.000000,7.071068e-01,7.071068e-01,0.781831,0.623490
max,2025-08-31 23:00:00,23.000000,6.000000,12.000000,1.000000e+00,1.000000e+00,0.974928,1.000000
std,NaN,6.922333,2.000538,3.406198,7.070525e-01,7.071622e-01,0.707117,0.707100

## Preisdaten
DA- und reBAP-Preise werden **nicht** in diesen Datensatz gemergt.
Sie werden direkt in  geladen,
da sie nur für die wirtschaftliche Evaluation benötigt werden und nicht direkt für den Forecast.